export type Stage = "lead" | "closing" | "won" | "lost" | null;
export type Relationship =
  | "customer"
  | "partner"
  | "vendor"
  | "team"
  | "personal"
  | "automated"
  | "unknown"
  | null;

export interface CrmRow {
  id: string;
  name: string;
  isGroup: boolean;
  relationship: Relationship;
  stage: Stage;
  activity: string;
  activityMs: number;
  direction: "in" | "out";
  lastMessage: string;
  followUp: string | null;
  region: string | null;
  regionFlag: string | null;
  email: string | null;
  tags: string[];
  assignedTo: string;
}

export const TEAM_MEMBERS = [
  "All",
  "Manuel A.",
  "Santiago R.",
  "Valentina L.",
  "Nicolás B.",
  "Camila T.",
];

export const CRM_ROWS: CrmRow[] = [
  {
    id: "1",
    name: "Charly Brandtrack",
    isGroup: false,
    relationship: null,
    stage: null,
    activity: "1m",
    activityMs: 1,
    direction: "out",
    lastMessage: "avisame nomas",
    followUp: null,
    region: "Argentina",
    regionFlag: "🇦🇷",
    email: null,
    tags: [],
    assignedTo: "Manuel A.",
  },
  {
    id: "2",
    name: "check",
    isGroup: false,
    relationship: null,
    stage: null,
    activity: "20m",
    activityMs: 20,
    direction: "in",
    lastMessage: "IN: - Comienza onboarding y testeos Humand Sales. Esto v",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Santiago R.",
  },
  {
    id: "3",
    name: "user-signups",
    isGroup: false,
    relationship: "automated",
    stage: null,
    activity: "4h",
    activityMs: 240,
    direction: "in",
    lastMessage: "🎉 *New user created* *Phone:* +33787916998 *Name:*",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Manuel A.",
  },
  {
    id: "4",
    name: "La Terma",
    isGroup: true,
    relationship: null,
    stage: "lead",
    activity: "4h",
    activityMs: 241,
    direction: "in",
    lastMessage: "......sabes donde te puede caber Burzaco, noooo?!?! Jajaja",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Valentina L.",
  },
  {
    id: "5",
    name: "Ratattouille 🐀",
    isGroup: false,
    relationship: null,
    stage: null,
    activity: "4h",
    activityMs: 242,
    direction: "in",
    lastMessage: "[image]",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Santiago R.",
  },
  {
    id: "6",
    name: "achis + iva",
    isGroup: false,
    relationship: "personal",
    stage: null,
    activity: "8h",
    activityMs: 480,
    direction: "in",
    lastMessage: "Yo no sé si llego",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Manuel A.",
  },
  {
    id: "7",
    name: "random",
    isGroup: true,
    relationship: null,
    stage: null,
    activity: "10h",
    activityMs: 600,
    direction: "in",
    lastMessage: "https://x.com/i/status/2066551592644751785 Odio cuando",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Nicolás B.",
  },
  {
    id: "8",
    name: "Juli",
    isGroup: false,
    relationship: null,
    stage: "closing",
    activity: "11h",
    activityMs: 660,
    direction: "in",
    lastMessage: "dep te cuento todo",
    followUp: "Hoy",
    region: "Argentina",
    regionFlag: "🇦🇷",
    email: null,
    tags: [],
    assignedTo: "Valentina L.",
  },
  {
    id: "9",
    name: "dev",
    isGroup: true,
    relationship: null,
    stage: null,
    activity: "11h",
    activityMs: 661,
    direction: "in",
    lastMessage: "https://x.com/i/status/2066958532096782798 lol, estamos",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Manuel A.",
  },
  {
    id: "10",
    name: "office",
    isGroup: true,
    relationship: "team",
    stage: null,
    activity: "11h",
    activityMs: 662,
    direction: "in",
    lastMessage: "corto también. seguí haciendo pruebas y va mucho mejor,",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Santiago R.",
  },
  {
    id: "11",
    name: "Volt & Humand Support",
    isGroup: true,
    relationship: "partner",
    stage: "won",
    activity: "12h",
    activityMs: 720,
    direction: "in",
    lastMessage: "Puedo manualmente",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Manuel A.",
  },
  {
    id: "12",
    name: "Marlene",
    isGroup: false,
    relationship: "customer",
    stage: "won",
    activity: "13h",
    activityMs: 780,
    direction: "in",
    lastMessage: "Claro un día cae sab creo",
    followUp: null,
    region: "Spain",
    regionFlag: "🇪🇸",
    email: "marlene@example.com",
    tags: [],
    assignedTo: "Camila T.",
  },
  {
    id: "13",
    name: "+52 1 55 8424 8702",
    isGroup: false,
    relationship: null,
    stage: "lead",
    activity: "13h",
    activityMs: 781,
    direction: "in",
    lastMessage: "Listo muchas gracias",
    followUp: null,
    region: "Mexico",
    regionFlag: "🇲🇽",
    email: null,
    tags: [],
    assignedTo: "Valentina L.",
  },
  {
    id: "14",
    name: "Volt & Gustavo Gehrke",
    isGroup: true,
    relationship: "partner",
    stage: "closing",
    activity: "13h",
    activityMs: 782,
    direction: "in",
    lastMessage: "no tuve mas tiempo para testear, pero ahora creo que pue",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Manuel A.",
  },
  {
    id: "15",
    name: "12-12 Boda",
    isGroup: true,
    relationship: null,
    stage: null,
    activity: "13h",
    activityMs: 783,
    direction: "in",
    lastMessage: "Si decime vos.... jueves ?",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Nicolás B.",
  },
  {
    id: "16",
    name: "Manuel Mao",
    isGroup: false,
    relationship: null,
    stage: "lead",
    activity: "13h",
    activityMs: 784,
    direction: "out",
    lastMessage: "Joyasaa",
    followUp: null,
    region: "Argentina",
    regionFlag: "🇦🇷",
    email: null,
    tags: [],
    assignedTo: "Santiago R.",
  },
  {
    id: "17",
    name: "Cande Tevez",
    isGroup: false,
    relationship: null,
    stage: null,
    activity: "14h",
    activityMs: 840,
    direction: "out",
    lastMessage: "esta bueno",
    followUp: null,
    region: "Argentina",
    regionFlag: "🇦🇷",
    email: null,
    tags: [],
    assignedTo: "Camila T.",
  },
  {
    id: "18",
    name: "Volt & Pedro Emboava",
    isGroup: true,
    relationship: "partner",
    stage: "closing",
    activity: "14h",
    activityMs: 841,
    direction: "in",
    lastMessage: "I hope to try it out tonight, Miguel!",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Manuel A.",
  },
  {
    id: "19",
    name: "Flord",
    isGroup: false,
    relationship: "customer",
    stage: "won",
    activity: "14h",
    activityMs: 842,
    direction: "in",
    lastMessage: "Oki",
    followUp: null,
    region: "Spain",
    regionFlag: "🇪🇸",
    email: "flord@example.com",
    tags: [],
    assignedTo: "Valentina L.",
  },
  {
    id: "20",
    name: "Integrations",
    isGroup: false,
    relationship: "automated",
    stage: null,
    activity: "14h",
    activityMs: 843,
    direction: "in",
    lastMessage: "anda a lobby private",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Nicolás B.",
  },
  {
    id: "21",
    name: "Volt & 500",
    isGroup: true,
    relationship: "partner",
    stage: "lead",
    activity: "14h",
    activityMs: 844,
    direction: "in",
    lastMessage: "Es independiente, esto fue a título personal y él ya no form",
    followUp: null,
    region: null,
    regionFlag: null,
    email: null,
    tags: [],
    assignedTo: "Manuel A.",
  },
  {
    id: "22",
    name: "Aspasia | HUMAND",
    isGroup: false,
    relationship: "customer",
    stage: "won",
    activity: "14h",
    activityMs: 845,
    direction: "in",
    lastMessage: `{ "mcpServers": { "volt": { "command": "npx", "args": ["-y",`,
    followUp: null,
    region: "Brazil",
    regionFlag: "🇧🇷",
    email: "aspasia@humand.com",
    tags: ["Customer"],
    assignedTo: "Santiago R.",
  },
];
